---
- name: Deploy Calculator App with Docker
  hosts: localhost
  become: true
  hosts: webserver
become: true
  tasks:

    - name: Run Calculator Container

  tasks:

    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: true

    - name: Run Docker container
      docker_container:
        name: scientific-calculator
        image: vishnuchavala/scientific-calculator:latest
        state: started
        recreate: yes
        pull: yes
        interactive: true
        tty: true
