---
- name: Deploy Calculator App with Docker
  hosts: localhost
  become: true

  tasks:
    - name: Run Calculator Container
      docker_container:
        name: scientific-calculator
        image: vishnuchavala/scientific-calculator:latest
        state: started
        recreate: yes
        pull: yes
        interactive: true
        tty: true 
          #comment
